SectionVerb {
	EnableSequence [
		cset "name='ADDA_DL_CH1 DL1_CH1' 1"
		cset "name='ADDA_DL_CH2 DL1_CH2' 1"
		cset "name='HPL Mux' LoudSPK Playback"
		cset "name='HPR Mux' LoudSPK Playback"
		cset "name='Ext_Speaker_Amp Switch' 1"
		cset "name='Headphone Volume' 18,18"
		cset "name='Lineout Volume' 12,12"
		cset "name='ADDA_DL_GAIN' 65535"
	]

	DisableSequence [
		cset "name='Ext_Speaker_Amp Switch' 0"
		cset "name='HPL Mux' Open"
		cset "name='HPR Mux' Open"
	]

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speakers"

	Value {
		PlaybackPriority 200
		PlaybackChannels 2
		PlaybackPCM "hw:${CardId},${var:PlayDevN}"
	}
}
